/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utilisateur;

import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import rmi.IClient;
import rmi.IOperation;

/**
 *
 * @author User
 */
public class Consultation extends javax.swing.JFrame {

    /**
     * Creates new form Consultation
     */
    private String numCpte;
    DefaultTableModel model;
    public Consultation(String num) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent e){
                new Login().setVisible(true);
            }
        });
        this.setVisible(true);
        this.numCpte = num;
        model = new DefaultTableModel();
        InitialisationTable();
        RemplissageInfo();
        EvtAutres();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        TxtNomClient = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TxtPrennom = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Txtbox_telephone = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Txtbox_dateCreation = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TxtNumeroCompte = new javax.swing.JTextField();
        TxtBoxTypeCompte = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Txtbox_solde = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Bt_imprimer = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        ComboxRechercheType = new javax.swing.JComboBox<>();
        TxtBox_recherche = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_infoClient = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        Bt_Actualiser = new javax.swing.JButton();
        Bt_versement = new javax.swing.JButton();
        Bt_Virement = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CLIENT BANQUE");
        setResizable(false);

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("  NOM CLIENT :");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        TxtNomClient.setEditable(false);
        TxtNomClient.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("PRENOMS CLIENT :");

        TxtPrennom.setEditable(false);
        TxtPrennom.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("    TYPE DE COMPTE :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setText("DATE CREATION :");

        Txtbox_telephone.setEditable(false);
        Txtbox_telephone.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setText("TELEPHONE :");

        Txtbox_dateCreation.setEditable(false);
        Txtbox_dateCreation.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel13.setText("  NUMERO  COMPTE:");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        TxtNumeroCompte.setEditable(false);
        TxtNumeroCompte.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        TxtBoxTypeCompte.setEditable(false);
        TxtBoxTypeCompte.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel14.setText("SOLDE :");

        Txtbox_solde.setEditable(false);
        Txtbox_solde.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtNumeroCompte, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Txtbox_solde, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                            .addComponent(TxtPrennom)
                            .addComponent(TxtNomClient)
                            .addComponent(TxtBoxTypeCompte)
                            .addComponent(Txtbox_telephone)
                            .addComponent(Txtbox_dateCreation))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNumeroCompte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNomClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtPrennom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtBoxTypeCompte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txtbox_telephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txtbox_dateCreation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txtbox_solde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Info client");

        Bt_imprimer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Bt_imprimer.setText("Imprimer");
        Bt_imprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_imprimerActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ComboxRechercheType.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ComboxRechercheType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Par type", "Par montant", "Par date" }));
        ComboxRechercheType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboxRechercheTypeActionPerformed(evt);
            }
        });

        TxtBox_recherche.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        TxtBox_recherche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtBox_rechercheMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ComboxRechercheType, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtBox_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtBox_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboxRechercheType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Historique des transactions");

        Table_infoClient.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Table_infoClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Table_infoClient);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Bt_Actualiser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Bt_Actualiser.setText("Actualiser");
        Bt_Actualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_ActualiserActionPerformed(evt);
            }
        });

        Bt_versement.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Bt_versement.setText("Versement");
        Bt_versement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_versementActionPerformed(evt);
            }
        });

        Bt_Virement.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Bt_Virement.setText("Virement");
        Bt_Virement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_VirementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Bt_Actualiser, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Bt_versement, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Bt_Virement, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bt_Actualiser)
                    .addComponent(Bt_versement)
                    .addComponent(Bt_Virement))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bt_imprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bt_imprimer)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bt_imprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_imprimerActionPerformed

            try {

                JTextArea output = new JTextArea();
                output.setText("\n\n\n\n:::::::::INFORMATION CLIENT:::::::::\n\n");
                output.append("\n\n NUMERO DE COMPTE : "+TxtNumeroCompte.getText().toUpperCase());
                output.append("\n\n    NOM : "+TxtNomClient.getText().toUpperCase());
                output.append("\n\nPRENOM  : "+TxtPrennom.getText().toUpperCase());
                output.append("\n\nTYPE DE COMPTE: "+TxtBoxTypeCompte.getText().toUpperCase());
                output.append("\n\nSOLDE CLIENT : " +Txtbox_solde.getText());
                output.append("\n\n TELEPHONE: "+Txtbox_telephone.getText().toUpperCase());
                output.append("\n\nDATE DE CREATION : " +Txtbox_dateCreation.getText());
                

                output.print(new MessageFormat("ALPHA BANQUE"), new MessageFormat("INFORMATION CLIENT."));

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Un problème a été détecté lors du lancement de l'impression.\n" +
                    "Vérifiez que votre imprimante est bien connectée", "Annuiare service Information", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }


    }//GEN-LAST:event_Bt_imprimerActionPerformed

    private void ComboxRechercheTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboxRechercheTypeActionPerformed
        TxtBox_recherche.setText("");
        InitialisationTable();
    }//GEN-LAST:event_ComboxRechercheTypeActionPerformed

    private void TxtBox_rechercheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtBox_rechercheMouseClicked

    }//GEN-LAST:event_TxtBox_rechercheMouseClicked

    private void Bt_ActualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_ActualiserActionPerformed
        InitialisationTable();
        RemplissageInfo();
        TxtBox_recherche.setText("");
    }//GEN-LAST:event_Bt_ActualiserActionPerformed

    private void Bt_versementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_versementActionPerformed
        if(TxtNumeroCompte.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Choisissez un compte svp !!!","INFO COMPTE",JOptionPane.INFORMATION_MESSAGE);
        }else{
            new VERSEMENT(TxtNumeroCompte.getText());
        }
    }//GEN-LAST:event_Bt_versementActionPerformed

    private void Bt_VirementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_VirementActionPerformed
        if(TxtNumeroCompte.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Choisissez un compte svp !!!","INFO COMPTE",JOptionPane.INFORMATION_MESSAGE);
        }else{
            new VIREMENT(TxtNumeroCompte.getText());
        }
    }//GEN-LAST:event_Bt_VirementActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Consultation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Consultation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Consultation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Consultation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Consultation().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Actualiser;
    private javax.swing.JButton Bt_Virement;
    private javax.swing.JButton Bt_imprimer;
    private javax.swing.JButton Bt_versement;
    private javax.swing.JComboBox<String> ComboxRechercheType;
    private javax.swing.JTable Table_infoClient;
    private javax.swing.JTextField TxtBoxTypeCompte;
    private javax.swing.JTextField TxtBox_recherche;
    private javax.swing.JTextField TxtNomClient;
    private javax.swing.JTextField TxtNumeroCompte;
    private javax.swing.JTextField TxtPrennom;
    private javax.swing.JTextField Txtbox_dateCreation;
    private javax.swing.JTextField Txtbox_solde;
    private javax.swing.JTextField Txtbox_telephone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
 
public void InitialisationTable(){
        try { 
            IOperation stub = (IOperation) Naming.lookup("rmi://localhost:1099/BANQUE");
            model = stub.ListeOperation(this.numCpte);
        } catch (NotBoundException ex) {
            JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur","ERREUR",JOptionPane.ERROR_MESSAGE);
        } catch (MalformedURLException ex) {
            JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur","ERREUR",JOptionPane.ERROR_MESSAGE);
        } catch (RemoteException ex) {
           JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur","ERREUR",JOptionPane.ERROR_MESSAGE);
        }
        Table_infoClient.setModel(model);
}
public void RemplissageInfo(){
        try { 
            IOperation stub = (IOperation) Naming.lookup("rmi://localhost:1099/BANQUE");
        DefaultTableModel modelInfo = stub.Consultation(this.numCpte);
        TxtNumeroCompte.setText(modelInfo.getValueAt(0, 0).toString());
        TxtNomClient.setText(modelInfo.getValueAt(0, 1).toString());
        TxtPrennom.setText(modelInfo.getValueAt(0, 2).toString());
        TxtBoxTypeCompte.setText(modelInfo.getValueAt(0, 3).toString());
        Txtbox_telephone.setText(modelInfo.getValueAt(0, 4).toString());
        Txtbox_dateCreation.setText(modelInfo.getValueAt(0, 5).toString());
        Txtbox_solde.setText(modelInfo.getValueAt(0, 6).toString());
        
        } catch (NotBoundException ex) {
            JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur","ERREUR",JOptionPane.ERROR_MESSAGE);
        } catch (MalformedURLException ex) {
            JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur","ERREUR",JOptionPane.ERROR_MESSAGE);
        } catch (RemoteException ex) {
           JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur","ERREUR",JOptionPane.ERROR_MESSAGE);
        }    
}
public void EvtAutres(){
        TxtBox_recherche.getDocument().addDocumentListener(new DocumentListener(){
            public void changedUpdate(DocumentEvent e){
                try {
                IClient stub = (IClient) Naming.lookup("rmi://localhost:1099/BANQUE");
                model = stub.ConsultationOperation(ComboxRechercheType.getSelectedItem().toString(), TxtBox_recherche.getText(),numCpte);
                } catch (NotBoundException ex) {
                     JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur","ERREUR",JOptionPane.ERROR_MESSAGE);
                } catch (MalformedURLException ex) {
                     JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur","ERREUR",JOptionPane.ERROR_MESSAGE);
                } catch (RemoteException ex) {
                     JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur","ERREUR",JOptionPane.ERROR_MESSAGE);
                }
                Table_infoClient.setModel(model);
            }
            public void insertUpdate(DocumentEvent e){
                try {
                IClient stub = (IClient) Naming.lookup("rmi://localhost:1099/BANQUE");
                model = stub.ConsultationOperation(ComboxRechercheType.getSelectedItem().toString(), TxtBox_recherche.getText(),numCpte);
                } catch (NotBoundException ex) {
                     JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur","ERREUR",JOptionPane.ERROR_MESSAGE);
                } catch (MalformedURLException ex) {
                     JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur","ERREUR",JOptionPane.ERROR_MESSAGE);
                } catch (RemoteException ex) {
                     JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur","ERREUR",JOptionPane.ERROR_MESSAGE);
                }
                Table_infoClient.setModel(model);
            }
            public void removeUpdate(DocumentEvent e){
            try {
                IClient stub = (IClient) Naming.lookup("rmi://localhost:1099/BANQUE");
                model = stub.ConsultationOperation(ComboxRechercheType.getSelectedItem().toString(), TxtBox_recherche.getText(),numCpte);
                } catch (NotBoundException ex) {
                     JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur","ERREUR",JOptionPane.ERROR_MESSAGE);
                } catch (MalformedURLException ex) {
                     JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur","ERREUR",JOptionPane.ERROR_MESSAGE);
                } catch (RemoteException ex) {
                     JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur","ERREUR",JOptionPane.ERROR_MESSAGE);
                }
                Table_infoClient.setModel(model);
            }
        });
        
    }

public void ViderTable(DefaultTableModel model){
        int i=model.getRowCount()-1;
        while(i!= -1){
            model.removeRow(i);
            i--;
        }
    }

}
